 class Failure {
  final String message;
  const Failure({this.message = "An unexpected error has occurred"});
}

// class AuthFailure extends Failure {
//   const AuthFailure(super.message);
// }

// class ServerFailure extends Failure {
//   const ServerFailure(super.message);
// }

// class NetworkFailure extends Failure {
//   const NetworkFailure(super.message);
// }

// class UnknownFailure extends Failure {
//   const UnknownFailure(super.message);
// }